project:
  type: website
  output-dir: docs
  
website:
  title: "Page No.4"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts/index.qmd
        text: homework

format:
  html:
    theme: cosmo
    toc: true
